### ISSUE TITLE
🔩 功能开发 | 关于产品建议

### ISSUE THREAD

**Issue by Jerrodly** [d2-projects/d2-admin-renren-security-enterprise#1]
人人开源的优势，在于打造出权限管理和通用功能，组件级别以及按钮级别二维颗粒度的权限架构，常用的组件方便别人的拓展，也基于推广得早，吸纳了一批用户；
而Ant Design pro直接体验优势，就是优雅美观，功能体验性极好，很顺畅，必定很细心才能做到这点；
d2-admin也有自己的优势，比如全局搜索、二次封装的组件库，但要做得比人人更好，除了推广，就是要借鉴ant design pro的亮点，

https://github.com/Konata9/my-umi-app/blob/master/README.zh-CN.md

**Comment by FairyEver** [comment]
是这样，这个仓库只计划实现人人目前有的功能，最终效果是可以用这套代码直连人人的后台就可以使用。至于和 Ant Design pro 对比，应该是 D2Admin2.0 的事。

**Comment by xkcoding** [comment]
@FairyEver 开始期待D2Admin2.0了，有开发计划吗？

**Comment by FairyEver** [comment]
@xkcoding 有计划 但是暂时保密
