### ISSUE TITLE
🖐 其它问题 | 菜单active有点小问题

### ISSUE THREAD

**Issue by 00feng00** [d2-projects/d2-admin-renren-security-enterprise#2]
Click the sidebar menu, click the first time there is no active, you need to click the same menu again to have active

点击侧边栏菜单，点击第一次没有active，需要再次点击同一个菜单才有active

**Comment by FairyEver** [comment]
fixed https://github.com/d2-projects/d2-admin-renren-security-enterprise/commit/4609bea679aebdb1341cfebe8efd316537026663
