### ISSUE TITLE
前端代码生成是关键

### ISSUE THREAD

**Issue by 13186137845** [d2-projects/d2-admin-renren-security-enterprise#6]
单表的前端代码生成功能能开发出来就好了

**Comment by FairyEver** [comment]
> d2-admin-renren-security-enterprise 是使用 [D2Admin](https://github.com/d2-projects/d2-admin) 适配 [人人企业版(专业版)](https://www.renren.io/enterprise) 的前端工程。实现所有人人企业版前端功能，并保留绝大部分 [D2Admin](https://github.com/d2-projects/d2-admin) 特性。

这是一个前端项目
