### ISSUE TITLE
动态添加路由，总是报错 Cannot find module

### ISSUE THREAD

**Issue by RocWangPeng** [d2-projects/d2-admin-renren-security-enterprise#7]
动态添加路由，总是报错 Error: Cannot find module './sys/dict__1127950486808031234'

![QQ截图20190515154330](https://user-images.githubusercontent.com/23447622/57757726-b1638f80-7728-11e9-8f6b-dfd9332c59ee.png)

**Comment by FairyEver** [comment]
表面上的错误是你的项目里没有 ./sys/dict__xxxxxx 这个文件，这个文件肯定不会存在，应该是你修改的有问题。我猜测你不是写的

``` js
component: () => import(`@/views/modules/${this.$route.name.replace(/-/g, '/')}`),
```

字典页面的问题已经在上面的提交中修正。

**Comment by FairyEver** [comment]
我猜你的问题是点击字典页面上的表格项目没有跳转，第二次再点就会报这个错，原因：

https://github.com/d2-projects/d2-admin-renren-security-enterprise/blob/94b5b9d372529f357ff49aa1a967ff06923951a1/src/views/modules/sys/dict.vue#L120

因为此时你的路由 `name` 已经变为了 `sys-dict__1067246875800000069`，再次 `replace(/-/g, '/')` 就产生了加载你截图中这个不存在的模块
