### ISSUE TITLE
👾 BUG | 部署流程文件页面el-upload不居中

### ISSUE THREAD

**Issue by hu-qi** [d2-projects/d2-admin-renren-security-enterprise#8]
算是个Bug吧，本来我以为是显示优化，毕竟只是显示上的偏差，不过，秉承严谨的原则，特地看了下源码，源码其实有加**text-center**，不过您写的时候应该是忘记加**d2**的前缀了，导致样式设置失败，所以改成Bug了。   
先上图吧，图片上能看到的肯定比我描述的要清晰，毕竟我属于表达比较差的。    
![activiti-add-center](https://user-images.githubusercontent.com/17986122/57860732-f3bfc600-7827-11e9-9b9d-49fa4a762847.png)

建议修改：   
src/views/modules/activiti/process-deploy.vue line 10   
class="text-center">      ===>     class="d2-text-center">   

修改后：   
![image](https://user-images.githubusercontent.com/17986122/57861298-e6efa200-7828-11e9-99bb-43317880809a.png)

**Comment by FairyEver** [comment]
已经修改 感谢指出
